spring:
  rabbitmq:
    host: 10.146.0.2  #rabbitmq 인스턴스의 내부아이피
    username: guest
    password: guest
    port: 5672
  data:
    elasticsearch:
      hosts: 10.146.0.3,10.146.0.4,10.146.0.5,10.146.0.6   # es-instance 4개의 내부아이피
      port: 9200
